package FrontEnd.Views;

import BusinessLayer.Enums.ManageKindEnum;
import BusinessLayer.Enums.ManageType;
import BusinessLayer.Enums.UserType;

import FrontEnd.Model.ProductModel;
import FrontEnd.Model.ShopModel;
import FrontEnd.SResponse;
import FrontEnd.SResponseT;
import ServiceLayer.DataObjects.PurchasePolicyDataObj;
import FrontEnd.MarketService;
import FrontEnd.Model.UserModel;
import ServiceLayer.ResponseT;
import com.vaadin.flow.component.Text;
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.html.Span;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.select.Select;
import com.vaadin.flow.component.textfield.IntegerField;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.component.timepicker.TimePicker;
import com.vaadin.flow.data.renderer.ComponentRenderer;
import com.vaadin.flow.router.BeforeEnterEvent;
import com.vaadin.flow.router.BeforeEnterObserver;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

@Route(value = "purchase_policy/:shopName")
@PageTitle("Purchase Policy")
public class PurchasePolicyView extends BaseView implements BeforeEnterObserver {

    private  MarketService marketService;
    private  UserModel currentUser;
    private  Grid<PurchasePolicyDataObj> policyGrid;
    private String shopName;
    private ShopModel shopProfile;
    private Button createSimplePolicyButton;
    private Button createComplexPolicyButton;
    private Button removeActivePolicyButton;



    @Override
    protected void updateAfterUserNameChange(UserModel userModel) {
        if(shopName == null) return;
        removeAll();
        add(getHorizontalLayout());
        marketService = MarketService.getInstance();
        currentUser = getCurrentUser();

        H3 pageTitle = new H3("Purchase Policies");
        add(pageTitle);

        policyGrid = new Grid<>(PurchasePolicyDataObj.class);
        policyGrid.setSizeFull();

        policyGrid.removeAllColumns(); // Remove all autogenerated columns
        // Define 'id' column
        policyGrid.addColumn(PurchasePolicyDataObj::getId).setHeader("Id");

        // Define 'name' column with custom style for the active policy
        policyGrid.addComponentColumn(policy -> {
            Div wrapper = new Div(new Text(policy.getName()));
            SResponseT<Integer> activePolicyResponse = marketService.getActivePurchasePolicyId(getCurrentUser().getName(), shopName);
            if (activePolicyResponse.isSuccess() && policy.getId() == (activePolicyResponse.getData())) {
                wrapper.getElement().getStyle().set("background-color", "#FBA997");
            }
            return wrapper;
        }).setHeader("Name").setWidth("880px");

        // Add 'Set as Active' button column
        policyGrid.addComponentColumn(policy -> {
            Button setActiveButton = new Button("Set as Active");
            setActiveButton.addClickListener(e -> {
                SResponse setActiveResponse = marketService.setActivePurchasePolicy(getCurrentUser().getName(), shopName, policy.getId());
                if (setActiveResponse.isSuccess()) {
                    updatePolicyGrid();
                    updateButtons();
                } else {
                    Notification.show("Error: "+setActiveResponse.getMessage());
                }
            });
            enableButton(setActiveButton);
            return setActiveButton;
        }).setHeader("Actions");

        add(policyGrid);
        updatePolicyGrid();

        createSimplePolicyButton = new Button("Create Simple Policy");
        createSimplePolicyButton.addClickListener(e -> openCreateSimplePolicyDialog());
        enableButton(createSimplePolicyButton);

        createComplexPolicyButton = new Button("Create Complex Policy");
        createComplexPolicyButton.addClickListener(e -> openCreateComplexPolicyDialog());
        enableButton(createComplexPolicyButton);

        removeActivePolicyButton = new Button("Remove Active Policy");
        removeActivePolicyButton.addClickListener(e -> {
            SResponse removeActivePolicyResponse = marketService.setActivePurchasePolicy(getCurrentUser().getName(), shopName, -1);
            updatePolicyGrid();
        });
        enableButton(removeActivePolicyButton);
        SResponseT<ShopModel> res = marketService.getShop(shopName);
        if(res.isSuccess()){
            shopProfile = res.getData();
        }
        updateButtons();

        HorizontalLayout buttonsLayout = new HorizontalLayout(createSimplePolicyButton, createComplexPolicyButton, removeActivePolicyButton);
        add(buttonsLayout);

        // Add custom CSS styles
        getStyle().set("padding", "1rem");
        buttonsLayout.getStyle().set("margin-top", "1rem");
    }

    private void updateButtons() {
        SResponseT<Integer> activePolicyResponse = marketService.getActivePurchasePolicyId(getCurrentUser().getName(), shopName);
        if(shopProfile != null && shopProfile.getRoles().get(getCurrentUser().getName()).getType().equals(ManageType.MANAGER) && shopProfile.getRoles().get(getCurrentUser().getName()).getPermissions().getManageAccess() == ManageKindEnum.READ_ONLY) {
            disableButton(createComplexPolicyButton);
            disableButton(createSimplePolicyButton);
            disableButton(removeActivePolicyButton);
        }
        else{
            enableButton(createComplexPolicyButton);
            enableButton(createSimplePolicyButton);
            enableButton(removeActivePolicyButton);
        }
        if (activePolicyResponse.isSuccess()) {
            int index = activePolicyResponse.getData();
            if(index == -1){
                disableButton(removeActivePolicyButton);
            }
        }
    }

    private void updatePolicyGrid() {
        SResponseT<Collection<PurchasePolicyDataObj>> policiesResponse = marketService.getAllPurchasePolicies(currentUser.getName(), shopName);
        if (policiesResponse.isSuccess()) {
            policyGrid.setItems(policiesResponse.getData());
        }
    }

    private void openCreateSimplePolicyDialog() {
        Dialog dialog = new Dialog();
        dialog.setWidth("400px");

        VerticalLayout layout = new VerticalLayout();
        layout.setPadding(false);

        ComboBox<String> policyTypeComboBox = new ComboBox<>("Policy Type");
        policyTypeComboBox.setItems("Age Constraint", "Quantity Constraint", "Date Constraint", "Time Constraint");
        policyTypeComboBox.setRequired(true);

        Button createPolicyButton = new Button("Create Policy", e -> {
            createSimplePolicy(policyTypeComboBox.getValue());
            dialog.close();
        });
        createPolicyButton.getStyle().set("background-image", "linear-gradient(to right,#ffcc33 , #ffb347)");
        createPolicyButton.getStyle().set("color", "white");

        layout.add(policyTypeComboBox, createPolicyButton);
        dialog.add(layout);
        dialog.open();
    }

    private void createSimplePolicy(String policyType) {
        if (policyType == null) {
            Notification.show("Please select a policy type");
            return;
        }

        switch (policyType) {
            case "Age Constraint":
                openAgeConstraintDialog();
                break;
            case "Quantity Constraint":
                openQuantityConstraintDialog();
                break;
            case "Date Constraint":
                openDateConstraintDialog();
                break;
            case "Time Constraint":
                openTimeConstraintDialog();
                break;
            default:
                Notification.show("Invalid policy type");
                break;
        }
    }

    private void openAgeConstraintDialog() {
        List<String> productNames = new ArrayList<>();
        List<String> categoryNames = new ArrayList<>();
        for (ProductModel p :marketService.getShop(shopName).getData().getProducts().values().stream().toList()){
            productNames.add(p.getName());
            if(!categoryNames.contains(p.getCategory()))
                categoryNames.add(p.getCategory());
        }

        Dialog dialog = new Dialog();
        dialog.setWidth("400px");

        VerticalLayout layout = new VerticalLayout();
        layout.setPadding(false);
        ComboBox<String> productOrCategoryComboBox = new ComboBox<>("Constraint On:");

        productOrCategoryComboBox.setItems("Product", "Category");
        productOrCategoryComboBox.setRequired(true);

        ComboBox<String> productName = new ComboBox<>("Name"); // Change TextField to ComboBox

        productOrCategoryComboBox.addValueChangeListener(event -> {
            if (event.getValue().equals("Product")) {
                productName.setItems(productNames);
            } else if (event.getValue().equals("Category")) {
                productName.setItems(categoryNames);
            }
        });


        ComboBox<String> policyActionComboBox = new ComboBox<>("Action");
        policyActionComboBox.setItems("Allow", "Restrict");
        policyActionComboBox.setRequired(true);

        IntegerField startAge = new IntegerField("Start Age");
        startAge.setRequired(true);
        IntegerField endAge = new IntegerField("End Age");
        endAge.setRequired(true);

        Button createPolicyButton = new Button("Create Policy", e -> {
            boolean isProduct = productOrCategoryComboBox.getValue().equals("Product");
            String toConstraint = productName.getValue();
            boolean positive = policyActionComboBox.getValue().equals("Allow");
            int sAge = startAge.getValue();
            int eAge = endAge.getValue();
            SResponse res = marketService.addAgePurchasePolicy(getCurrentUser().getName(),shopName,isProduct,toConstraint,positive,sAge,eAge);
            if(!res.isSuccess())Notification.show("Error: "+res.getMessage());
            else {
                updatePolicyGrid();
            }
            dialog.close();
        });
        createPolicyButton.getStyle().set("background-image", "linear-gradient(to right,#ffcc33 , #ffb347)");
        createPolicyButton.getStyle().set("color", "white");

        layout.add(productOrCategoryComboBox,productName, policyActionComboBox, startAge, endAge, createPolicyButton);
        dialog.add(layout);
        dialog.open();
    }

    private void openQuantityConstraintDialog() {
        List<String> productNames = new ArrayList<>();
        List<String> categoryNames = new ArrayList<>();
        for (ProductModel p :marketService.getShop(shopName).getData().getProducts().values().stream().toList()){
            productNames.add(p.getName());
            if(!categoryNames.contains(p.getCategory()))
                categoryNames.add(p.getCategory());
        }

        Dialog dialog = new Dialog();
        dialog.setWidth("400px");

        VerticalLayout layout = new VerticalLayout();
        layout.setPadding(false);
        ComboBox<String> productOrCategoryComboBox = new ComboBox<>("Constraint On:");
        productOrCategoryComboBox.setItems("Product", "Category");
        productOrCategoryComboBox.setRequired(true);

        ComboBox<String> productName = new ComboBox<>("Name"); // Change TextField to ComboBox

        productOrCategoryComboBox.addValueChangeListener(event -> {
            if (event.getValue().equals("Product")) {
                productName.setItems(productNames);
            } else if (event.getValue().equals("Category")) {
                productName.setItems(categoryNames);
            }
        });

        ComboBox<String> policyActionComboBox = new ComboBox<>("Action");
        policyActionComboBox.setItems("Allow", "Restrict");
        policyActionComboBox.setRequired(true);
        IntegerField minQuantity = new IntegerField("Min Quantity");
        minQuantity.setRequired(true);
        IntegerField maxQuantity = new IntegerField("Max Quantity");
        maxQuantity.setRequired(true);

        Button createPolicyButton = new Button("Create Policy", e -> {
            boolean isProduct = productOrCategoryComboBox.getValue().equals("Product");
            String toConstraint = productName.getValue();
            boolean positive = policyActionComboBox.getValue().equals("Allow");
            int min = minQuantity.getValue();
            int max = maxQuantity.getValue();
            SResponse res = marketService.addQuantityPurchasePolicy(getCurrentUser().getName(),shopName,isProduct,toConstraint,positive,min,max);
            if(!res.isSuccess())Notification.show("Error "+res.getMessage());
            else {
                updatePolicyGrid();
            }
            dialog.close();
        });
        createPolicyButton.getStyle().set("background-image", "linear-gradient(to right,#ffcc33 , #ffb347)");
        createPolicyButton.getStyle().set("color", "white");

        layout.add(productOrCategoryComboBox,productName, policyActionComboBox,minQuantity, maxQuantity, createPolicyButton);
        dialog.add(layout);
        dialog.open();
    }

    private void openDateConstraintDialog() {
        List<String> productNames = new ArrayList<>();
        List<String> categoryNames = new ArrayList<>();
        for (ProductModel p :marketService.getShop(shopName).getData().getProducts().values().stream().toList()){
            productNames.add(p.getName());
            if(!categoryNames.contains(p.getCategory()))
                categoryNames.add(p.getCategory());
        }

        Dialog dialog = new Dialog();
        dialog.setWidth("400px");

        VerticalLayout layout = new VerticalLayout();
        layout.setPadding(false);

        ComboBox<String> productOrCategoryComboBox = new ComboBox<>("Constraint On:");
        productOrCategoryComboBox.setItems("Product", "Category");
        productOrCategoryComboBox.setRequired(true);

        ComboBox<String> productName = new ComboBox<>("Name"); // Change TextField to ComboBox

        productOrCategoryComboBox.addValueChangeListener(event -> {
            if (event.getValue().equals("Product")) {
                productName.setItems(productNames);
            } else if (event.getValue().equals("Category")) {
                productName.setItems(categoryNames);
            }
        });

        ComboBox<String> policyActionComboBox = new ComboBox<>("Action");
        policyActionComboBox.setItems("Allow", "Restrict");
        policyActionComboBox.setRequired(true);

        DatePicker startDate = new DatePicker("Start Date");
        startDate.setRequired(true);
        DatePicker endDate = new DatePicker("End Date");
        endDate.setRequired(true);

        Button createPolicyButton = new Button("Create Policy", e -> {
            boolean isProduct = productOrCategoryComboBox.getValue().equals("Product");
            String toConstraint = productName.getValue();
            boolean positive = policyActionComboBox.getValue().equals("Allow");
            LocalDate sDate = startDate.getValue();
            LocalDate eDate = endDate.getValue();
            SResponse res = marketService.addDatePurchasePolicy(getCurrentUser().getName(),shopName,isProduct,toConstraint,positive,sDate,eDate);
            if(!res.isSuccess())Notification.show("Error "+res.getMessage());
            else {
                updatePolicyGrid();
            }
            dialog.close();
        });
        createPolicyButton.getStyle().set("background-image", "linear-gradient(to right,#ffcc33 , #ffb347)");
        createPolicyButton.getStyle().set("color", "white");

        layout.add(productOrCategoryComboBox,productName, policyActionComboBox, startDate, endDate, createPolicyButton);
        dialog.add(layout);
        dialog.open();
    }

    private void openTimeConstraintDialog() {
        List<String> productNames = new ArrayList<>();
        List<String> categoryNames = new ArrayList<>();
        for (ProductModel p :marketService.getShop(shopName).getData().getProducts().values().stream().toList()){
            productNames.add(p.getName());
            if(!categoryNames.contains(p.getCategory()))
                categoryNames.add(p.getCategory());
        }

        Dialog dialog = new Dialog();
        dialog.setWidth("400px");

        VerticalLayout layout = new VerticalLayout();
        layout.setPadding(false);

        ComboBox<String> productOrCategoryComboBox = new ComboBox<>("Constraint On:");
        productOrCategoryComboBox.setItems("Product", "Category");
        productOrCategoryComboBox.setRequired(true);

        ComboBox<String> productName = new ComboBox<>("Name"); // Change TextField to ComboBox

        productOrCategoryComboBox.addValueChangeListener(event -> {
            if (event.getValue().equals("Product")) {
                productName.setItems(productNames);
            } else if (event.getValue().equals("Category")) {
                productName.setItems(categoryNames);
            }
        });

        ComboBox<String> policyActionComboBox = new ComboBox<>("Action");
        policyActionComboBox.setItems("Allow", "Restrict");
        policyActionComboBox.setRequired(true);

        TimePicker startTime = new TimePicker("Start Time");
        startTime.setRequired(true);
        TimePicker endTime = new TimePicker("End Time");
        endTime.setRequired(true);

        Button createPolicyButton = new Button("Create Policy", e -> {
            boolean isProduct = productOrCategoryComboBox.getValue().equals("Product");
            String toConstraint = productName.getValue();
            boolean positive = policyActionComboBox.getValue().equals("Allow");
            int sTime = startTime.getValue().getHour();
            int eTime = endTime.getValue().getHour();
            SResponse res = marketService.addTimePurchasePolicy(getCurrentUser().getName(),shopName,isProduct,toConstraint,positive,sTime,eTime);
            if(!res.isSuccess())Notification.show("Error "+res.getMessage());
            else {
                updatePolicyGrid();
            }
            dialog.close();
        });
        createPolicyButton.getStyle().set("background-image", "linear-gradient(to right,#ffcc33 , #ffb347)");
        createPolicyButton.getStyle().set("color", "white");

        layout.add(productOrCategoryComboBox,productName, policyActionComboBox, startTime, endTime, createPolicyButton);
        dialog.add(layout);
        dialog.open();
    }

    private void openCreateComplexPolicyDialog() {
        Dialog dialog = new Dialog();
        dialog.setWidth("400px");

        VerticalLayout layout = new VerticalLayout();
        layout.setPadding(false);

        ComboBox<String> complexPolicyTypeComboBox = new ComboBox<>("Complex Policy Type");
        complexPolicyTypeComboBox.setItems("AND Policy", "OR Policy","IF Policy");
        complexPolicyTypeComboBox.setRequired(true);

        Button createPolicyButton = new Button("Next", e -> {
            String selectedType = complexPolicyTypeComboBox.getValue();
            if ("AND Policy".equals(selectedType)) {
                openCreateAndPolicyDialog();
            } else if ("OR Policy".equals(selectedType)) {
                openCreateOrPolicyDialog();
            } else if ("IF Policy".equals(selectedType)) {
                openCreateIfPolicyDialog();
            }
            dialog.close();
        });
        enableButton(createPolicyButton);

        layout.add(complexPolicyTypeComboBox, createPolicyButton);
        dialog.add(layout);
        dialog.open();
    }

    private void openCreateIfPolicyDialog() {
        Dialog dialog = new Dialog();
        dialog.setWidth("400px");

        VerticalLayout layout = new VerticalLayout();
        layout.setPadding(false);

        IntegerField firstPolicy = new IntegerField("First Policy");
        firstPolicy.setRequired(true);

        IntegerField secondPolicy = new IntegerField("Second Policy");
        secondPolicy.setRequired(true);


        Button createPolicyButton = new Button("Create Policy", e -> {
            int pid1 = firstPolicy.getValue();
            int pid2 = secondPolicy.getValue();
            SResponse res = marketService.addIfPurchasePolicy(getCurrentUser().getName(),shopName,pid1,pid2);
            if(!res.isSuccess())Notification.show("Error "+res.getMessage());
            else {
                Notification.show("Success!");
                updatePolicyGrid();
            }
            dialog.close();
        });
        createPolicyButton.getStyle().set("background-image", "linear-gradient(to right,#ffcc33 , #ffb347)");
        createPolicyButton.getStyle().set("color", "white");

        layout.add(firstPolicy,secondPolicy,createPolicyButton);
        dialog.add(layout);
        dialog.open();
    }

    private void openCreateAndPolicyDialog() {
        Dialog dialog = new Dialog();
        dialog.setWidth("400px");

        VerticalLayout layout = new VerticalLayout();
        layout.setPadding(false);

        IntegerField firstPolicy = new IntegerField("First Policy");
        firstPolicy.setRequired(true);

        IntegerField secondPolicy = new IntegerField("Second Policy");
        secondPolicy.setRequired(true);


        Button createPolicyButton = new Button("Create Policy", e -> {
            int pid1 = firstPolicy.getValue();
            int pid2 = secondPolicy.getValue();
            SResponse res = marketService.addAndPurchasePolicy(getCurrentUser().getName(),shopName,pid1,pid2);
            if(!res.isSuccess())Notification.show("Error "+res.getMessage());
            else {
                Notification.show("Success!");
                updatePolicyGrid();
            }
            dialog.close();
        });
        createPolicyButton.getStyle().set("background-image", "linear-gradient(to right,#ffcc33 , #ffb347)");
        createPolicyButton.getStyle().set("color", "white");

        layout.add(firstPolicy,secondPolicy,createPolicyButton);
        dialog.add(layout);
        dialog.open();
    }

    private void openCreateOrPolicyDialog() {
        Dialog dialog = new Dialog();
        dialog.setWidth("400px");

        VerticalLayout layout = new VerticalLayout();
        layout.setPadding(false);

        IntegerField firstPolicy = new IntegerField("First Policy");
        firstPolicy.setRequired(true);

        IntegerField secondPolicy = new IntegerField("Second Policy");
        secondPolicy.setRequired(true);

        Button createPolicyButton = new Button("Create Policy", e -> {
            int pid1 = firstPolicy.getValue();
            int pid2 = secondPolicy.getValue();
            SResponse res = marketService.addOrPurchasePolicy(getCurrentUser().getName(),shopName,pid1,pid2);
            if(!res.isSuccess())Notification.show("Error "+res.getMessage());
            else {
                Notification.show("Success!");
                updatePolicyGrid();
            }
            dialog.close();
        });
        createPolicyButton.getStyle().set("background-image", "linear-gradient(to right,#ffcc33 , #ffb347)");
        createPolicyButton.getStyle().set("color", "white");

        layout.add(firstPolicy,secondPolicy, createPolicyButton);
        dialog.add(layout);
        dialog.open();
    }

    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        event.getRouteParameters().get("shopName").ifPresent(shopName -> {
            this.shopName = shopName;
            updateAfterUserNameChange(getCurrentUser());
        });
    }
}